# This workflow will build a .js bundle and upload it ot a bucket 
# 
# The bundle is beign created by Single Spa Webpack scripts 
#
# For more info about the action is beign used go to Cloud storage uploader https://github.com/marketplace/actions/cloud-storage-uploader

name: Build and Deploy to GKE

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build dist
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    
    - name: Install dependencies
      run: yarn 
    
    - name: Run Build
      run: yarn build
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: dist
          path: dist

  upload-to-bucket:
    name: Upload dist to Bucket
    runs-on: ubuntu-latest
    needs: build
  
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Create forlder
      run: mkdir /dist
      
    - name: Display structure of downloaded files
      run: ls -R
  
    - name: Download dist folder
      uses: actions/download-artifact@v3
      with:
            name: dist
            path: /dist
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'      

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: 'dist'
        destination: 'bucket-name'
        gzip: true
        
